[Interface]
PrivateKey = <CLIENT_PRIVATE_KEY>
Address = 10.6.0.2/24
DNS = 10.6.0.1

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
PresharedKey = <PRESHARED_KEY_OPTIONAL>
Endpoint = tu-subdominio.duckdns.org:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
